name: Docker Image CI

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: '568720945'
  IMAGE_NAME: 'tdengine'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
      
